# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-jessie-node-browsers

    steps:
    - checkout

    - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
    - run: sudo docker-php-ext-install zip

    # composer cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install -n --prefer-dist

    - save_cache:
        key: composer-v1-{{ checksum "composer.lock" }}
        paths:
        - vendor

    # prepare .env
    - run: cp .env.example .env
    - run: php artisan key:generate
    - run: sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
    - run: sed -i '/DB_DATABASE=homestead/d' .env

    # prepare the database
    - run: touch ./database/database.sqlite
    - run: php artisan migrate --seed --force

    # run tests with phpunit or codecept
    - run: ./vendor/bin/phpunit